input {
  beats {
    port => 5041
    ssl => false
  }
}
filter { 
    ruby {
       code => 'event.set("[@metadata][now]", Time.new.strftime("%Y.%m.%d") )'
    }
    ruby {
       code => 'event.set("[incomingtime]", Time.new.strftime("%Y-%m-%d %H:%M:%S.%L" ) )'
    }

    grok {
       match => ["source","%{GREEDYDATA}/%{GREEDYDATA:filename}"]
       keep_empty_captures => true
    }

  if "cloud-init-output.log" not in [source] {
    grok {
      match => { "message" => [
                                 "(?<zeit>^\d\d\-\d\d\s[\d\:]*)", 				#bibe pe_pepara5.log  06-08 14:16:32.0076
                                 "(?<zeit>^(%{DAY} %{MONTH} (\s\d|\d\d) %{TIME} %{YEAR}))", 	# Fri Jun 12 14:07:04 2020
				 "(?<zeit>^(%{DAY} %{MONTH} (\s\d|\d\d) %{TIME} CEST %{YEAR}))",#aws-download-planrt.log Fri Jun 12 14:07:04 CEST 2020
                                 "%{TIMESTAMP_ISO8601:zeit}"					#filebeat 2020-06-12T14:24:09.297+0200\tERROR
				]      
     } 
}
      date {
        locale => "en"
        match => ["zeit", 
                        "MM-dd HH:mm:ss",
                        "EEE MMM  d HH:mm:ss yyyy",      
                        "EEE MMM dd HH:mm:ss yyyy",
                        "EEE MMM  d HH:mm:ss 'CEST' yyyy",
                        "EEE MMM dd HH:mm:ss 'CEST' yyyy",
			"YYYY-MM-dd'T'HH:mm:ss.SSSZ",
			"YYYY-MM-dd HH:mm:ss"
                 ]
        timezone => "Europe/Berlin"
        target => "@timestamp"
   }
   mutate { remove_field => [ "zeit","beat" ] }
  }
}

#config für elasticsearch entfernt 
output {
     file {
       path => "/opt/logstash/logfiles/%{[fields][teilverfahren]}/%{[fields][dataType]}/%{[@metadata][now]}/%{[fields][environment]}-%{[host][name]}-%{[fields][instance-id]}-%{filename}.gz"
       codec => line { format => "%{message}" }
       flush_interval => 0
       gzip => true
     }
}
